val1 = int(input("1st number : "))
val2 = int(input("2nd number : "))
print(val1, "+", val2, "=", val1+val2)
print(val1, "-", val2, "=", val1-val2)
print(val1, "*", val2, "=", val1*val2)
print(val1, "/", val2, "=", int(val1/val2))